### ISSUE TITLE
Use CI to build releases with binaries

### ISSUE THREAD

**Issue by oSumAtrIX** [exconvinced/revanced-web-app#1]
# Issue

Currently, this repository includes binaries. Git is designed to host source files (except LFS and assets).

# Solution

Remove binaries such as:

- https://github.com/exconvinced/revanced-web-app/blob/master/static/sqlite3.exe
- https://github.com/exconvinced/revanced-web-app/blob/master/static/packages.db
- https://github.com/exconvinced/revanced-web-app/blob/master/revanced/revanced-cli.jar
- https://github.com/exconvinced/revanced-web-app/blob/master/revanced/dependencies/integrations.apk
- https://github.com/exconvinced/revanced-web-app/blob/master/revanced/dependencies/patches.jar
- https://github.com/exconvinced/revanced-web-app/blob/master/revanced/aapt/aapt_64.exe

Instead do the following:

- Let CI download a pinned version of ReVanced CLI, generate the database, package everything at build time, and release the assets under GitHub Releases
- Remove AAPT is included with ReVanced CLI (is there any reason binaries are present in this repository?)
- You can rely on browser local storage instead of a SQLite database in the frontend. This would allow you to host the site statically and only require people to download the server that connects to the frontend to execute the commands for ReVanced CLI
- Remove the patches and integrations, as this tool 

   > Gets latest patches from the [official repo](https://raw.githubusercontent.com/ReVanced/revanced-patches/main/patches.json).
 
# Motivation

Git is designed to host source files instead of binaries. To comply with this design, binaries such as the above should not be present in the source code. This ensures transparency and improves sustainability because if the underlying code needs updated binaries, the current ones won't work and would require pushing new binaries.

PS: Good work!

**Comment by exconvinced** [comment]
@oSumAtrIX Hey man! You found me! I truly appreciate these valuable comments! Really points out how bad the practice I was doing (using GitHub like OneDrive)! You know, I intend to improve this web app to conform with the new CLI. I'll follow your advice and study these GitHub workarounds you mentioned. Thanks a lot!

**Comment by exconvinced** [comment]
> Remove AAPT is included with ReVanced CLI (is there any reason binaries are present in this repository?)

Do you mean that ReVanced CLI have AAPT built in too?

I learned that I can use AAPT to extract info from APK files. I needed to display on page the package name, app name, and version of any uploaded file.

I agree that the binaries shouldn't be present here. I simply didn't know about CI at the time. My bad 😄

**Comment by oSumAtrIX** [comment]
> I learned I can use AAPT to extract info from APK files. I needed to display on the page the package name, app name, and version of any uploaded file.

I see, then its fine.

**Comment by ArjixWasTaken** [comment]
> You can rely on browser local storage instead of a SQLite database in the frontend. This would allow you to host the site statically and only require people to download the server that connects to the frontend to execute the commands for ReVanced CLI

Browsers also have a database-like storage, named [`IndexedDB`](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), if you want to save complex data then that is a better alternative than `localStorage`

**Comment by ArjixWasTaken** [comment]
> I learned I can use AAPT to extract info from APK files. I needed to display on the page the package name, app name, and version of any uploaded file.

You can directly use a library just for that

Python: [apk_parse](https://pypi.org/project/apk-parse)
JavaScript: [apk_info_parser](https://www.npmjs.com/package/app-info-parser)

You really should only parse command line output for stuff like ffmpeg.
(Because ffmpeg as a library is too hard to use)

**Comment by exconvinced** [comment]
Hi @ArjixWasTaken. I like your suggestion. Truthfully, this got me excited for a while because it had more than everything I needed. Unfortunately, my Python 3 won't find [apk_parse](https://pypi.org/project/apk-parse/) when doing `import apk_parse`. When I looked at my pip packages directory, it was installed in a folder called **main**. I looked at the code and saw syntax made for Python 2.7, a dead end. Similarly, I found [aapt](https://pypi.org/project/aapt/) for Python but I also got the "no module found" error despite installing it correctly.

I'll think about this later, but I have a few pressing problems to look at with GitHub Actions for now 😂.

**Comment by exconvinced** [comment]
Will look into browser storage some other time too because I'm not well-versed with JavaScript. What I could do for improvement is totally omit SQLite and simply rely on Python dictionary or classes.

edit: sqlite does nothing for my web app. i initially used it to make a dictionary of app names from google play store. but because i have aapt now i can remove it along with other unused code.

**Comment by exconvinced** [comment]
Practicing GitHub Actions right now. I'm still figuring out how to release multiple files in this setup:
```yml
  - name: Download ReVanced dependencies
    id: python-script
    run: python get_dependencies.py # this prints out cli.jar, patches.jar, patches.json, inte.apk, one per line

  - name: Create GitHub Release
    id: create_release
    uses: softprops/action-gh-release@v1
    with:
      tag_name: revanced-dependencies-test
      files: # i want to put those printed strings here
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
I read that I could use `GITHUB_OUTPUT` variable here, but not sure how exactly. I tried several attempts but so far I got these from **Create GitHub Release** step in the workflow:
```
# GITHUB_OUTPUT is empty
🤔  not include valid file.

# Workflow finds only the first item in the input
⬆️ Uploading cli.jar...

# Messed up the pattern
🤔 Pattern 'cli.jarfiles=patches.jarfiles=patches.jsonfiles=inte.apk >> GITHUB_OUTPUT' does not match any files.

**Comment by ArjixWasTaken** [comment]
> Hi @ArjixWasTaken. I like your suggestion. Truthfully, this got me excited for a while because it had more than everything I needed. Unfortunately, my Python 3 won't find [apk_parse](https://pypi.org/project/apk-parse/) when doing `import apk_parse`. When I looked at my pip packages directory, it was installed in a folder called **main**. I looked at the code and saw syntax made for Python 2.7, a dead end. Similarly, I found [aapt](https://pypi.org/project/aapt/) for Python but I also got the "no module found" error despite installing it correctly.

That's sad to hear, [here](https://github.com/appknox/pyaxmlparser) is a python 3 library instead!

**Comment by ArjixWasTaken** [comment]
in 3 hours I will be off work, if you need help then, I'll be glad to help

**Comment by exconvinced** [comment]
> That's sad to hear, [here](https://github.com/appknox/pyaxmlparser) is a python 3 library instead!

Golden! This works! Adding it to my dependencies...

edit: I decided to stick with aapt because pyaxmlparser takes seconds to load, while aapt works instantly in my code. I will just open a new repo and make a separate python module for aapt.

**Comment by exconvinced** [comment]
> in 3 hours I will be off work, if you need help then, I'll be glad to help

Thank you so much. I think I could use some help regarding GitHub CI. I'm new to this. Apart from [this](https://github.com/exconvinced/revanced-web-app/issues/1#issuecomment-1697285827) issue, I also want to learn how to do automatic versioning properly for cases like major/minor stable releases and dev builds.

**Comment by exconvinced** [comment]
I finally figured [this](https://github.com/exconvinced/revanced-web-app/issues/1#issuecomment-1697285827) out. 

In Python, I can print out the list as string:
```py
  results = ["cli.jar", "patches.jar", "patches.json", "integrations.apk"]
  print(', '.join(results))
```
Then in CI, I can capture that string like this:
```yml
  - name: Download ReVanced dependencies
    id: python-script
    run: echo "files=$(python get_dependencies.py)" >> $GITHUB_OUTPUT
```
So that GitHub Release can find the files:
```yml
  - name: Create GitHub Release
    id: create_release
    uses: softprops/action-gh-release@v1
    with:
      tag_name: Revanced-Test-Release
      files: ${{ steps.python-script.outputs.files }}
```
It was not intuitive to me at first. The guides I saw only presented the manual case which is not flexible:
```yml
   files: |
     file1.x
     file2.x
     file3.x
```

**Comment by exconvinced** [comment]
Hey guys! I made my first ever proper release, [v0.0.0-dev](https://github.com/exconvinced/revanced-web-app/releases)! If you can test it, let me know if you encounter issues. 

Can you also look at my workflow here: [release.yml](https://github.com/exconvinced/revanced-web-app/blob/master/.github/workflows/release.yml)? It triggers every time I push to master. It was fine at first but now I think it's a bit extreme for it to run that frequently.
