### ISSUE TITLE
bug: Selected patches do not show up

### ISSUE THREAD

**Issue by oSumAtrIX** [exconvinced/revanced-web-app#10]
# Issue

The list of selected apps is empty:

![image](https://github.com/exconvinced/revanced-web-app/assets/13122796/c4dfda26-9f17-46c1-8015-cd4d1339877e)

# Additional context

I believe it is caused by parsing patches that are used by default incorrectly.

**Comment by exconvinced** [comment]
I should be able to fix it soon. Took me a while to revise the code so it can work with the latest cli and patches. 

I saw that you changed how the patches are included/excluded in cli. You also changed the "excluded" property to "use" in patches.json. It's difficult man. 🤣

**Comment by exconvinced** [comment]
I downloaded the [latest release](https://github.com/exconvinced/revanced-web-app/releases/tag/release). It looks fine on my end. I made two `ci` runs today. You might have downloaded the release from the earlier one.

![image](https://github.com/exconvinced/revanced-web-app/assets/139973199/016046f7-6952-4d41-b4c5-18c6fd0107ca)

**Comment by exconvinced** [comment]
null description fixed. See #9 

![image](https://github.com/exconvinced/revanced-web-app/assets/139973199/c8bfc6d6-a797-46a1-8a1a-418a70d64d07)

**Comment by exconvinced** [comment]
The selected patches don't show up in Chrome but they do on Firefox.

**Comment by exconvinced** [comment]
Fixed in commit 290871d1ea87271d84226c1ce79f2f51f38ef900.
