### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by oSumAtrIX** [exconvinced/revanced-web-app#2]
# Issue

The goal of this project is to provide an easy interface to users. But at first sight, it is unknown how to set up and get the project running.

# Solution

Include building/ setup instructions in the `README` file. Alternatively, you can create packaged releases through CI, if possible.

**Comment by exconvinced** [comment]
I totally agree with this! Will get back to this issue after I learn about GitHub CI and handling binaries in a few days.

**Comment by exconvinced** [comment]
Packaged releases through CI, done! More in #1
