### ISSUE TITLE
bug: Attempt to display nullable patch descriptions

### ISSUE THREAD

**Issue by oSumAtrIX** [exconvinced/revanced-web-app#9]
# Issue

The description of patches is nullable, but the frontend still attempts to show them even when they are null:

![image](https://github.com/exconvinced/revanced-web-app/assets/13122796/ff215a4f-70b7-43a4-8822-7bfe86c83cba)

# Solution

Check for null and do not display the description if it is.

**Comment by exconvinced** [comment]
Good catch. Could be fixed using few conditionals in Javascript. I haven't delved deeply into the new patches.json structure yet so I'm sure it's one of the things I overlooked.

**Comment by exconvinced** [comment]
Fixed! https://github.com/exconvinced/revanced-web-app/commit/2d92e50aea206a3342a027beb155554e46c3165f

![image](https://github.com/exconvinced/revanced-web-app/assets/139973199/2d238b81-c00a-43bc-8462-399c9e463d8c)
